### ISSUE TITLE
Supported Platforms v. Build/Installation Scripts

### ISSUE THREAD

**Issue by liam-curran** [GeoscienceAustralia/ginan#52] opened 2023-10-04 05:51 UTC
Not really a bug, nor necessarily wrong, but maybe an inconsistency on the main page & build/installation Scripts:

There are scripts to install dependencies for Fedora 38, but it is not noted as an Installation from source / Supported Platforms. Is this missed cross reference or Fedora 38 isn't strictly supported?

**Comment by jiargei** [comment] 2023-10-23 07:05
Dear GA!

@liam-curran : there is an error in the bash script scripts/installation/fedora38.sh, it seems GA used a Dockerfile as blue print.

It will fail in line 92: replace "RUN" with "$sudo_cmd" or just "sudo" in case you're not root. I changed it and ran it under Rocky Linux 8 and it worked!

It would be nice if you would provide an ansible playbook for preparing a server for ginan.
It is just an idea..


kind regards

**Comment by seballgeyer** [comment] 2023-10-31 23:45
Thanks for this, the issue is fixed in the `develop_weekly` branch.

**Closed by seballgeyer** 2023-10-31 23:45 UTC

**Comment by jiargei** [comment] 2023-11-03 14:51
I wrote an ansible role to install GINAN on an Rocky Linux 8 (RHEL 8). Should I provide it to you anyhow?
